apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: sample-container
      image: kenkolab-test:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
