apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample-container
        image: sample-app:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
