apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: sample-container
      image: sample-app:v1
      # ローカルのDockerイメージを取得
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
